"""
Django settings for time_tracker project.

Generated by 'django-admin startproject' using Django 3.2.

For more information on this file, see
https://docs.djangoproject.com/en/3.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/3.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent


# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/3.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-oqw60+afz7t!tu+%x_=4+bt!4%kjmb0-9y*fkpu07!395!^q^!'

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = ['django-time-tracker.herokuapp.com', '127.0.0.1']


# Application definition

INSTALLED_APPS = [
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',

    'apps.core',
    'apps.userprofile',
    'tinymce',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

    'whitenoise.middleware.WhiteNoiseMiddleware',
]

SESSION_EXPIRE_AT_BROWSER_CLOSE = False

ROOT_URLCONF = 'time_tracker.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

WSGI_APPLICATION = 'time_tracker.wsgi.application'


# Database
# https://docs.djangoproject.com/en/3.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',

        'NAME': 'd1judhnbo5us2',
        'HOST': 'ec2-54-160-96-70.compute-1.amazonaws.com',
        'PORT': 5432,

        'USER': 'zilbodrawsjxdf',
        'PASSWORD': 'dea48fd58b6c56ca28ad32717ad21e1d9f389d23eba63c0483a9ef4647cff916',
        
    }
}
#LOCAL
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',
    #     'NAME': 'django_timetracker',

    #     'USER': 'postgres',
    #     'PASSWORD': 'daniil10',
    #     'HOST': 'localhost',    
    # }

#HEROKU
    # 'default': {
    #     'ENGINE': 'django.db.backends.postgresql',

    #     'NAME': 'd1judhnbo5us2',
    #     'HOST': 'ec2-54-160-96-70.compute-1.amazonaws.com',
    #     'PORT': 5432,

    #     'USER': 'zilbodrawsjxdf',
    #     'PASSWORD': 'dea48fd58b6c56ca28ad32717ad21e1d9f389d23eba63c0483a9ef4647cff916',
           
    # }


AUTH_USER_MODEL = "userprofile.Userprofile"
# AUTHENTICATION_BACKENDS = (
#     ('django.contrib.auth.backends.ModelBackend'),
# )

# Password validation
# https://docs.djangoproject.com/en/3.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },

    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/3.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_L10N = True

USE_TZ = True



# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/3.2/howto/static-files/

STATIC_URL = '/static/'

STATICFILES_DIRS = [
    BASE_DIR / 'static'
]

STATIC_ROOT = BASE_DIR / 'assets'



MEDIA_ROOT =  os.path.join(BASE_DIR, 'media')
MEDIA_URL = '/media/'

# Default primary key field type
# https://docs.djangoproject.com/en/3.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

#MAIL SENDING SETTINGS
EMAIL_HOST =  'smtp.gmail.com'
EMAIL_PORT = '587'
EMAIL_HOST_USER = 'vremennyja71@gmail.com'
EMAIL_HOST_PASSWORD = 'django_timetracker'
EMAIL_USE_TLS = True